name: Test Notifications

on:
  workflow_run:
    workflows: ["Test Suite"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'success'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install @aws-sdk/client-ses
          sudo apt-get update && sudo apt-get install -y jq

      - name: Get workflow details
        uses: actions/github-script@v6
        id: workflow-details
        with:
          script: |
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            
            let failedJobs = jobs.data.jobs.filter(job => job.conclusion === 'failure');
            let failureDetails = failedJobs.map(job => {
              return `${job.name}: ${job.steps.filter(step => step.conclusion === 'failure').map(step => step.name).join(', ')}`;
            }).join('\n');
            
            return {
              branch: run.data.head_branch,
              commit_message: run.data.head_commit.message,
              author: run.data.head_commit.author.name,
              author_email: run.data.head_commit.author.email,
              failed_jobs: failureDetails,
              run_url: context.payload.workflow_run.html_url
            };

      - name: Send critical notification
        if: fromJson(steps.workflow-details.outputs.result).branch == 'main'
        env:
          DETAILS: ${{ steps.workflow-details.outputs.result }}
          AWS_SMTP_USERNAME: ${{ secrets.AWS_SMTP_USERNAME }}
        run: |
          DETAILS_JSON='${{ steps.workflow-details.outputs.result }}'
          BRANCH=$(echo "$DETAILS_JSON" | jq -r '.branch')
          COMMIT=$(echo "$DETAILS_JSON" | jq -r '.commit_message')
          AUTHOR=$(echo "$DETAILS_JSON" | jq -r '.author')
          FAILED_JOBS=$(echo "$DETAILS_JSON" | jq -r '.failed_jobs')
          RUN_URL=$(echo "$DETAILS_JSON" | jq -r '.run_url')

          BODY="⚠️ CRITICAL: Tests Failed on Main Branch

          A test failure has occurred on the main branch.

          ## Failure Details
          - Branch: $BRANCH
          - Commit Message: $COMMIT
          - Author: $AUTHOR
          - Failed Jobs:
          $FAILED_JOBS

          ## Action Required
          Please investigate and fix the failing tests as soon as possible.

          View Workflow Run: $RUN_URL"

          node scripts/send-notification.js \
            "[CRITICAL] Tests Failed on Main Branch - Lagomo" \
            "$BODY" \
            "${{ secrets.NOTIFICATION_EMAIL }}"

      - name: Send coverage notification
        if: contains(fromJson(steps.workflow-details.outputs.result).failed_jobs, 'Test Coverage:')
        env:
          DETAILS: ${{ steps.workflow-details.outputs.result }}
          AWS_SMTP_USERNAME: ${{ secrets.AWS_SMTP_USERNAME }}
        run: |
          DETAILS_JSON='${{ steps.workflow-details.outputs.result }}'
          BRANCH=$(echo "$DETAILS_JSON" | jq -r '.branch')
          COMMIT=$(echo "$DETAILS_JSON" | jq -r '.commit_message')
          AUTHOR=$(echo "$DETAILS_JSON" | jq -r '.author')
          RUN_URL=$(echo "$DETAILS_JSON" | jq -r '.run_url')

          BODY="⚠️ Test Coverage Alert

          The test coverage has fallen below the required threshold.

          ## Details
          - Branch: $BRANCH
          - Commit Message: $COMMIT
          - Author: $AUTHOR

          ## Action Required
          Please add more tests to improve coverage.

          View Workflow Run: $RUN_URL"

          node scripts/send-notification.js \
            "[WARNING] Test Coverage Below Threshold - Lagomo" \
            "$BODY" \
            "${{ secrets.NOTIFICATION_EMAIL }}"
