name: Test Notifications

on:
  workflow_run:
    workflows: ["Test Suite"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: read
  id-token: write

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'success'
    environment: development
    permissions:
      contents: read
      actions: read
      checks: read
      id-token: write
    env:
      AWS_SMTP_USERNAME: ${{ github.actions.vars.AWS_SMTP_USERNAME }}
      AWS_SMTP_PASSWORD: ${{ github.actions.secrets.AWS_SMTP_PASSWORD }}
      NOTIFICATION_EMAIL: ${{ github.actions.vars.NOTIFICATION_EMAIL }}
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::266654255232:role/github-actions-ses-role
          aws-region: us-east-1

      # First, get the secrets from the triggering workflow
      - name: Download workflow artifact
        uses: actions/github-script@v6
        id: download
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            const matchArtifact = artifacts.data.artifacts.find((artifact) => {
              return artifact.name == "workflow-data"
            });
            if (!matchArtifact) return;
            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });

      - name: Debug Secrets
        env:
          AWS_SMTP_USERNAME: ${{ github.actions.vars.AWS_SMTP_USERNAME }}
          NOTIFICATION_EMAIL: ${{ github.actions.vars.NOTIFICATION_EMAIL }}
        run: |
          echo "Checking required secrets..."
          [[ -n "$AWS_SMTP_USERNAME" ]] && echo "AWS_SMTP_USERNAME is set" || echo "AWS_SMTP_USERNAME is missing"
          [[ -n "$NOTIFICATION_EMAIL" ]] && echo "NOTIFICATION_EMAIL is set" || echo "NOTIFICATION_EMAIL is missing"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install @aws-sdk/client-ses
          sudo apt-get update && sudo apt-get install -y jq

      - name: Get workflow details
        uses: actions/github-script@v6
        id: workflow-details
        with:
          script: |
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            
            let failedJobs = jobs.data.jobs.filter(job => job.conclusion === 'failure');
            let failureDetails = failedJobs.map(job => {
              return `${job.name}: ${job.steps.filter(step => step.conclusion === 'failure').map(step => step.name).join(', ')}`;
            }).join('\n');
            
            return {
              branch: run.data.head_branch,
              commit_message: run.data.head_commit.message,
              author: run.data.head_commit.author.name,
              author_email: run.data.head_commit.author.email,
              failed_jobs: failureDetails,
              run_url: context.payload.workflow_run.html_url
            };

      - name: Send critical notification
        if: fromJson(steps.workflow-details.outputs.result).branch == 'main'
        env:
          DETAILS: ${{ steps.workflow-details.outputs.result }}
          AWS_SMTP_USERNAME: ${{ github.actions.vars.AWS_SMTP_USERNAME }}
        run: |
          DETAILS_JSON='${{ steps.workflow-details.outputs.result }}'
          BRANCH=$(echo "$DETAILS_JSON" | jq -r '.branch')
          COMMIT=$(echo "$DETAILS_JSON" | jq -r '.commit_message')
          AUTHOR=$(echo "$DETAILS_JSON" | jq -r '.author')
          FAILED_JOBS=$(echo "$DETAILS_JSON" | jq -r '.failed_jobs')
          RUN_URL=$(echo "$DETAILS_JSON" | jq -r '.run_url')

          BODY="⚠️ [DEV] Tests Failed on Main Branch

          A test failure has occurred on the main branch.

          ## Failure Details
          - Branch: $BRANCH
          - Commit Message: $COMMIT
          - Author: $AUTHOR
          - Failed Jobs:
          $FAILED_JOBS

          ## Action Required
          Please investigate and fix the failing tests as soon as possible.

          View Workflow Run: $RUN_URL"

          node scripts/send-notification.js \
            "[DEV] Tests Failed on Main Branch - Lagomo" \
            "$BODY" \
            "${{ github.actions.secrets.NOTIFICATION_EMAIL }}"

      - name: Send coverage notification
        if: contains(fromJson(steps.workflow-details.outputs.result).failed_jobs, 'Test Coverage:')
        env:
          DETAILS: ${{ steps.workflow-details.outputs.result }}
          AWS_SMTP_USERNAME: ${{ github.actions.vars.AWS_SMTP_USERNAME }}
        run: |
          DETAILS_JSON='${{ steps.workflow-details.outputs.result }}'
          BRANCH=$(echo "$DETAILS_JSON" | jq -r '.branch')
          COMMIT=$(echo "$DETAILS_JSON" | jq -r '.commit_message')
          AUTHOR=$(echo "$DETAILS_JSON" | jq -r '.author')
          RUN_URL=$(echo "$DETAILS_JSON" | jq -r '.run_url')

          BODY="⚠️ [DEV] Test Coverage Alert

          The test coverage has fallen below the required threshold.

          ## Details
          - Branch: $BRANCH
          - Commit Message: $COMMIT
          - Author: $AUTHOR

          ## Action Required
          Please add more tests to improve coverage.

          View Workflow Run: $RUN_URL"

          node scripts/send-notification.js \
            "[DEV] Test Coverage Below Threshold - Lagomo" \
            "$BODY" \
            "${{ github.actions.secrets.NOTIFICATION_EMAIL }}"

      - name: Send test notification
        if: contains(fromJson(steps.workflow-details.outputs.result).failed_jobs, 'Test:')
        env:
          DETAILS: ${{ steps.workflow-details.outputs.result }}
          AWS_SMTP_USERNAME: ${{ github.actions.vars.AWS_SMTP_USERNAME }}
        run: |
          DETAILS_JSON='${{ steps.workflow-details.outputs.result }}'
          BRANCH=$(echo "$DETAILS_JSON" | jq -r '.branch')
          COMMIT=$(echo "$DETAILS_JSON" | jq -r '.commit_message')
          AUTHOR=$(echo "$DETAILS_JSON" | jq -r '.author')
          FAILED_JOBS=$(echo "$DETAILS_JSON" | jq -r '.failed_jobs')
          RUN_URL=$(echo "$DETAILS_JSON" | jq -r '.run_url')

          BODY="⚠️ [DEV] Tests Failed

          A test failure has occurred.

          ## Failure Details
          - Branch: $BRANCH
          - Commit Message: $COMMIT
          - Author: $AUTHOR
          - Failed Jobs:
          $FAILED_JOBS

          ## Action Required
          Please investigate and fix the failing tests as soon as possible.

          View Workflow Run: $RUN_URL"

          node scripts/send-notification.js \
            "[DEV] Tests Failed - Lagomo" \
            "$BODY" \
            "${{ github.actions.secrets.NOTIFICATION_EMAIL }}"
